services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    container_name: expense-backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: exp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
